export const GET_ALL_PIECES_SUCCESS = 'GET_ALL_PIECE_SUCCESS';
export const GET_ALL_PIECES_FAIL = "GET_ALL_PIECE_FAIL";
export const GET_ALL_PIECES_LOADING = "GET_ALL_PIECE_LOADING";
//---------
export const DELETE_PIECE_SUCCESS = "DELETE_PIECE_SUCCESS";
//---------
export const DELETE_PIECE_FAIL = "DELETE_PIECE_FAIL";
export const DETAIL_PIECE_FAIL = "DETAIL_PIECE_FAIL";
export const DETAIL_PIECE_SUCCESS = "DETAIL_PIECE_SUCCESS";
//------------
export const ADD_PIECE_FAIL = "ADD_PIECE_FAIL";
export const ADD_PIECE_SUCCESS = "ADD_PIECE_SUCCESS";
//--------
export const EDIT_PIECE_FAIL = "EDIT_PIECE_FAIL";
export const EDIT_PIECE_SUCCESS = "EDIT_PIECE_SUCCESS";
//----------
export const SEARCH_PIECES_LOADING ="SEARCH_PIECES_LOADING";
export const SEARCH_PIECES_SUCCESS = "SEARCH_PIECES_SUCCESS";
export const SEARCH_PIECES_FAIL = "SEARCH_PIECES_FAIL";
//----------
export const SEARCHE_PIECES_LOADING ="SEARCH_PIECES_LOADING";
export const SEARCHE_PIECES_SUCCESS = "SEARCH_PIECES_SUCCESS";
export const SEARCHE_PIECES_FAIL = "SEARCH_PIECES_FAIL";